[project]
fullname = "BVerfG RAG Corpus"
shortname = "BVerfG-RAG"
author = "Seán Fobbe"

[debug]
toggle = false
pages = 20

[cores]
max = true
number = 8

[download]
timeout = 60



# RAG-spezifische Einstellungen
[rag]
include_metadata = true
max_text_length = 10000  # Maximale Textlänge pro Chunk
chunk_overlap = 200      # Überlappung zwischen Chunks



